# Created by sh.shilpashree at 17-01-2025
*** Settings ***
Library    SeleniumLibrary

*** Variables ***
${URL}      https://www.amazon.in
${BROWSER}  chrome
${EMAIL}    shilpa.sya2@gmail.com  # Replace with your sandbox test account
${PASSWORD}  Abc@123         # Replace with your sandbox test password
${OTP}      123456  # Replace with a valid OTP for testing purposes

*** Keywords ***
